name: CI

on:
  push:
    branches: ["**"]
    tags: [v*]
  pull_request:
    branches: ["**"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - uses: coursier/cache-action@v6

      - name: Run tests
        run: ./mill _.test

      - name: Check format
        run: ./mill mill.scalalib.scalafmt.ScalafmtModule/checkFormatAll

      - name: Publish to GitHub Packages (Mill)
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./mill mill.scalalib.PublishModule/ \
            --publishArtifacts inodeParser.publishArtifacts \
            --sonatypeUri https://maven.pkg.github.com/optisense-iot/ble-inode \
            --stagingRelease false \
            --signed false \
            --sonatypeCreds "$GITHUB_ACTOR:$GITHUB_TOKEN"

