name: CI

on:
  push:
    branches: ["**"]
    tags: [v*]
  pull_request:
    branches: ["**"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - uses: coursier/cache-action@v5

      - name: Run tests
        run: ./mill _.test

      - name: Check format
        run: ./mill mill.scalalib.scalafmt.ScalafmtModule/checkFormatAll

      - name: Build docker image
        run: ./mill server.docker.build

      - name: Set outputs
        id: version
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Tag docker image
        run: |
          docker tag server ghrc.io/optisense-iot/ble-inode:${{ steps.version.outputs.sha_short }}
          docker tag server ghrc.io/optisense-iot/ble-inode:latest

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push docker imageo
        run: |
          docker push ghrc.io/optisense-iot/ble-inode:${{ steps.version.outputs.sha_short }}
          docker push ghrc.io/optisense-iot/ble-inode:latest
